# Generated by Django 4.2.11 on 2024-04-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='products.product'),
        ),
    ]
